# notation
# () = grouping
# {} = 0 or more
# [] = 0 or 1

Program = {Stmt semicolon} ;
Stmt = IdentDeclaration | IdentAssignment ;
IdentDeclaration = ConstDecl | VarDecl ;
ConstDecl = "constant" IdentDecl Value ;
VarDecl = "variable" IdentDecl [Value] ;
IdentType = ident "is" Type
IdentAssignment = ident "is" Value ;

Type = ident | ("list" "of" Type) | ("map" "of" Type "to" Type) ;
Value = Literal | ident | Range ;
Literal = numberLiteral | booleanLiteral | stringLiteral | ListLiteral | MapLiteral | StructLiteral ;
ListLiteral = "containing" ("nothing" | ListElements) "done" ;
ListElements = ListOne [ListElements] | ListOne "and" ListOne ;
ListOne = Value "," ;